//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapatazObra
    {
        public int idCapatazObra { get; set; }
        public System.DateTime fecha { get; set; }
        public int capatazId { get; set; }
        public int obraId { get; set; }
    
        public virtual Capataces Capataces { get; set; }
        public virtual Obras Obras { get; set; }
    }
}
